apiVersion: v2
name: eksApp
description: A Helm chart that deploys the External Key Service application.
type: application
version: "0.1.0"
dependencies:
- name: connect
  version: "2.0.0"
  repository: https://1password.github.io/connect-helm-charts
  condition: enableConnect
- name: external-secrets
  version: "0.18.1"
  repository: https://charts.external-secrets.io
  condition: enableEksOperator
- name: reflector
  version: "9.1.22"
  repository: https://emberstack.github.io/helm-charts
  condition: enableReflector