global:
  commonLabels: {}
  commonAnnotations: {}

connectTokenSecretName: "onepassword-connect-token"

namespace:
  enabled: true
  name: "external-secrets"
  commonAnnotations: {}
  commonLabels: {}

clusterStores:
  enabled: false
  stores: {}
  # Example cluster vault
  # - name: "example-cluster-vault"
  #   # Defaults to true, set to false to disable
  #   enabled: true
  #   # Vaults in the cluster vault
  #   vaults:
  #     - name: "example-vault"
  #       priority: 1
  #     # More can be added, priority should be unique

# First connect to pass the content of this block to the helm chart
connect: 
  # Second because the chart expects the values to be in a connect block
  connect: 
    serviceType: ClusterIP

    api:
      # Prometheus Service Monitor
      # ref: https://github.com/coreos/prometheus-operator
      serviceMonitor:
        # Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
        enabled: false
        # Specify the interval at which metrics should be scraped
        interval: 30s
        # Define the path used by ServiceMonitor to scrape metrics
        path: "/metrics"
        # Define the HTTP URL parameters used by ServiceMonitor
        params: {}
        # Extra annotations for the ServiceMonitor
        annotations: {}

external-secrets:
  # Specifies whether an external secret operator deployment be created.
  # If set to false, the operator will not be deployed and only the CRDs will be installed.
  createOperator: true

  # If set, install and upgrade CRDs through helm chart.
  installCRDs: true
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true

  # If set external secrets are only reconciled in the
  # provided namespace
  scopedNamespace: ""
  # Must be used with scopedNamespace. If true, create scoped RBAC roles under the scoped namespace
  # and implicitly disable cluster stores and cluster external secrets
  scopedRBAC: false
  # if true, the operator will process cluster external secret. Else, it will ignore them.
  processClusterExternalSecret: true
  # if true, the operator will process cluster push secret. Else, it will ignore them.
  processClusterPushSecret: true
  # if true, the operator will process cluster store. Else, it will ignore them.
  processClusterStore: true
  # if true, the operator will process push secret. Else, it will ignore them.
  processPushSecret: true

  serviceMonitor:
    # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
    enabled: false
  grafanaDashboard:
    # If true creates a Grafana dashboard.
    enabled: false
