# First connect to pass the content of this block to the helm chart
connect: 
  # Second because the chart expects the values to be in a connect block
  connect: 
    serviceType: ClusterIP

external-secrets:
  # Specifies whether an external secret operator deployment be created.
  # If set to false, the operator will not be deployed and only the CRDs will be installed.
  createOperator: true

  # If set, install and upgrade CRDs through helm chart.
  installCRDs: true
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true

  # If set external secrets are only reconciled in the
  # provided namespace
  scopedNamespace: ""
  # Must be used with scopedNamespace. If true, create scoped RBAC roles under the scoped namespace
  # and implicitly disable cluster stores and cluster external secrets
  scopedRBAC: false
  # if true, the operator will process cluster external secret. Else, it will ignore them.
  processClusterExternalSecret: true
  # if true, the operator will process cluster push secret. Else, it will ignore them.
  processClusterPushSecret: true
  # if true, the operator will process cluster store. Else, it will ignore them.
  processClusterStore: true
  # if true, the operator will process push secret. Else, it will ignore them.
  processPushSecret: true
  grafanaDashboard:
    # If true creates a Grafana dashboard.
    enabled: false